### ISSUE TITLE
Enable automatic release to PyPI/Anaconda cloud

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#116]
http://docs.pythonpackages.com/en/latest/github-service.html

This github service hook can automatically push the release to PyPi. We should use it once we are ready for first release on PyPi.

**Comment by JackKelly** [comment]
one advantage of putting NILMTK onto PyPI is that NILMTK will be indexed by [Depsy](http://depsy.org/).

**Comment by nipunbatra** [comment]
Thanks for pointing Depsy. Looks interesting! We're long due a PyPI/Anaconda release :)

**Comment by ayushp20** [comment]
Try using:
`conda install -c nilmtk nilmtk`

**Comment by PMeira** [comment]
It'd helpful to add tagged package uploads to Anaconda for the time being. Here's the script I use for DSS Python:

https://github.com/dss-extensions/dss_python/blob/master/ci/build_linux_conda.sh

Since NILMTK itself doesn't need individual OS packages, I think we only need the API token to enable that, besides some tweaks to versioning and the conda `meta.yaml`.
