### ISSUE TITLE
Define Disaggregator superclass

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#271]
Define Disaggregator superclass to hold common behaviour & to specify common interface to NILM algorithms & common docstrings.

@oliparson discovered how to specify common common docstrings using a superclass.  Described in [this comment](https://github.com/nilmtk/nilmtk/issues/268#issuecomment-65666922).

**Comment by JackKelly** [comment]
It shouldn't be too hard to write a `Disaggregator` superclass and hence massively simplify the implementation of new NILM algorithms.  I'll try to write a draft Disaggregator class within the next couple of weeks so we can try to get it into v0.3.  I think this is pretty essential.  We've had great success with encouraging other developers to add dataset converters to NILMTK but no one has yet added their own NILM algorithm to NILMTK.  This is a big issue and, I think, needs addressing before we release v0.3.  The basic idea would be, as outlined by Nipun, that a new NILM algorithm would only have to override the `train_on_chunk()` and `disaggregate_chunk()` methods.

**Comment by nipunreddevil** [comment]
I see that this is not a huge change and has several benefits. I am happy to have this design before v0.3; especially given the fact that it would get tougher to change later!

**Comment by oliparson** [comment]
Pasting from Nipun's email:

I guess if the disaggregator class is in place, then all the algo writer needs to do is to take a DataFrame input and output a data frame of all appliances. So, the first step for any algo writer could be to provide a function which takes an in-memory data frame of mains readings an disaggregates it, without having to worry about some of the specifics of nilmtk.

**Comment by oliparson** [comment]
# Vision for the Disaggregator superclass
N.B. only the method signatures and docstrings exist at the moment, and hopefully the implementation will follow shortly :)

Disaggregation algorithms will be implemented by extending the disaggregator superclass. This allows disaggregation algorithms to implement a common interface, while also reusing generic NILMTK code. There will be two (complementary) methods of implementing a disaggregation algorithm:

## 1. Working with Pandas Dataframes
This approach requires the `train_on_chunk()` and `disaggregate_chunk()` methods to be overridden by the subclass. This approach is strongly recommended, as it allows the disaggregation to be performed out-of-core, as well as allowing code to call this function without worrying about NILMTK data structures. Furthermore, this approach will make use of generic `Disaggregator` functionality to iterate over dataframes produced by a generator, as well as saving the disaggregation output to disk for each chunk.

## 2. Working with NILMTK MeterGroups
This approach requires the `train()` and `disaggregate()` methods to be overridden by the subclass. This approach is not recommended without also overriding the chunk-by-chunk disaggregation, as it will mean all disaggregation needs to take place in memory. However, it will be necessary to override these methods if the disaggregation algorithm is going to make use of mutual information between multiple aggregate site-meters, i.e. split-phase power.

In addition, a disaggregation sub-class can choose to implement the `import_model()` and `export_model()` methods to allow the learned model to be saved to disk, rather than re-learned each time a new environment is created.

**Comment by JackKelly** [comment]
I'm working on splitting `CombinatorialOptimisation.disaggregate()` into `disaggregate()` and `disaggregate_chunk()` now.

**Comment by JackKelly** [comment]
done

**Comment by JackKelly** [comment]
One issue I'm not clear on is this: how do we write a common interface for `train_on_chunk`?  There are several requirements different types of disaggregation algorithm I can think of:

1. Ones like CombinatorialOptimisation which only require a single appliance at once.
2. Ones like my Neural NILM code which requires both the aggregate mains data and one appliance at a time during training.

How do we build a common function signature for `train_on_chunk`?  Do we just always use something like `train_on_chunk(self, appliance_chunk, mains_chunk=None)`?

Although, to be honest, I'm not sure my Neural NILM code will ever implement `train_on_chunk` because it always needs full access to the MeterGroup (so it can get activations of each appliance to augment the training data etc).

**Comment by oliparson** [comment]
This is a really good point. Could we change the signature to take a MeterGroup, which can always just contain a single ElecMeter for supervised learning?

**Comment by JackKelly** [comment]
> Could we change the signature to take a MeterGroup

I haven't articulated this very well yet... but I was hoping that both `train_on_chunk` and `disaggreate_chunk` would take only non-NILMTK types.  e.g. just objects like Pandas DataFrames, dicts, numpy arrays, strings etc.  

I think it would be nice to allow NILMTK to interact more freely with the wider scientific Python ecosystem by allowing people to more freely use NILMTK directly on DataFrames / numpy arrays etc.

For example, when I was messing around with my Neural NILM work, I only used NILMTK for data loading (and comparing with CO and FHMM). I didn't use NILMTK's `Disaggregator` interface at all for my Neural NILM experiments.  Part of the reason was that I was doing a lot of 'augmenting' the training data (i.e. generating lots of numpy arrays) and it was easier to stay in numpy land rather than try to wrap my numpy arrays into an `ElecMeter` object or something (which, at the moment, isn't even possible in NILMTK without first dumping the numpy array to disk, which would have slowed things down *a lot*).  Hence my ambition to try to allow the Disaggregator subclasses to interact *either* with NILMTK objects like `MeterGroups` *or* directly with DataFrame / numpy arrays.

Does that sound sensible?  Maybe it's not possible?

**Comment by oliparson** [comment]
This sounds like a really good idea, and in general I'm happy with any changes that simplify the required knowledge for algorithm contributors. Do you think each algorithm really needs to implement train_on_chunk though so long as they're iterating through the chunks?

**Comment by nipunreddevil** [comment]
I'd second using Pandas data frames instead of nilmtk data structures for `disaggregate_chunk`.

**Comment by JackKelly** [comment]
> Do you think each algorithm really needs to implement train_on_chunk though so long as they're iterating through the chunks?

In an ideal world, yes, I think each algorithm should implement `train_on_chunk` and `disaggregate_chunk`.  With a bit of thought on our end, we could perhaps design things so disag algo authors *only* have to implement those two methods and the superclass would handle iterating through the chunks (and the superclass would call `train_on_chunk` and `disaggregate_chunk`).  But, given the diversity of NILM algorithms, we'd need to give algo authors to option to override `disaggregate` and `train` to iterate through chunks in custom ways.

**Comment by JackKelly** [comment]
Maybe the superclass could define a function signature for train_on_chunk
which covers all the options (ie has parameters for the mains as well as
the appliances) and any NILM algorithm (like CO) which doesn't need mains
won't require 'mains' and will just ignore it if it is provided.  That way
users can write code which can use any NILM algorithm without changing the
function call.  Any thoughts?

**Comment by PMeira** [comment]
Closing in favor of the new API.
