### ISSUE TITLE
WikiEnergy index is not monotonic

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#295]
This is likely to cause problems in a lot of downstream functions.

``` python

In [16]: from nilmtk import DataSet

In [17]: ds = DataSet("/home/nipun/Desktop/wikienergy.h5")

In [18]: store = ds.store

In [19]: i = store.store['/building1/elec/meter1'].index

In [20]: i.is_monotonic
Out[20]: False

In [21]: i = store.store['/building10/elec/meter1'].index

In [22]: i.is_monotonic
Out[22]: False
```

In comparison with ukdale, iawe

``` python

In [23]: ds = DataSet("/home/nipun/ukdale.h5")

In [24]: store =ds.store

In [25]: i = store.store['/building2/elec/meter1'].index

In [26]: i.is_monotonic
Out[26]: True

In [27]: i = store.store['/building1/elec/meter1'].index

In [28]: i.is_monotonic
Out[28]: True
```

**Comment by PMeira** [comment]
For future reference on this old issue, I believe the root cause of this is just that PostgreSQL doesn't sort columns if there is no specific `ORDER BY` statement, it just dumps matching rows.

Since WikiEnergy/Dataport has too much data, I won't work on it anytime soon unless other issues show up. Let's just keep the issue open...
