### ISSUE TITLE
ValueError: Unknown format code 'd' for object of type 'str'

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#353]
copied from comment https://github.com/nilmtk/nilmtk/issues/204#issuecomment-76145264 by @t7reyeslua :

Hi!....I am trying to run nilmtk but I am having some issues when I reach: f1 = f1_score(disag_elec,elec).
I have tried following both the Demo of NILMTK v0.2 for BuildSys 2014 and the original tutorial in the user manual. I am using the REDD data for both. I have already pulled the latest version from git of both nilmtk and nilm_metadata but still the same result. What could be the problem?

```python
===================================================
/home/t7/anaconda/lib/python2.7/site-packages/sklearn/metrics/metrics.py:1771: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py:786: PendingDeprecationWarning: object.__format__ with a non-empty format string is deprecated
  .format(self.building(), self.instance(), stat_name))
Traceback (most recent call last):

  File "<ipython-input-5-9b5a04a7cbc9>", line 1, in <module>
    f1_score(disag_elec, elec)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/metrics.py", line 222, in f1_score
    'when_on'):

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/electric.py", line 785, in align_two_meters
    sections = master.good_sections()

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 635, in good_sections
    nodes, results_obj, loader_kwargs)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 685, in _get_stat_from_cache_or_compute
    key_for_cached_stat = self.key_for_cached_stat(results_obj.name)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 786, in key_for_cached_stat
    .format(self.building(), self.instance(), stat_name))

ValueError: Unknown format code 'd' for object of type 'str'
```

**Comment by JackKelly** [comment]
Please can you modify `nilmtk/elecmeter.py`. At line 785, please insert this:

```python
print("BUILDING: '{}', INSTANCE: '{}'".format(self.building(), self.instance()))
```

And then re-run the code and copy-and-paste the output into the issue queue, please?

**Comment by t7reyeslua** [comment]
I think it works now. Thanks!...I left line 785 as this:

return ("BUILDING: '{}', INSTANCE: '{}'".format(self.building(), self.instance()))

and the output  is the following:

f1
Out[3]: 
5           0.474791
6           0.129629
7           0.570910
8           0.584494
9           0.326056
11          0.209420
12          0.068543
13          0.005917
14          0.000000
15          0.154464
16          0.042199
17          0.416340
18          0.319713
19          0.000000
(3, 4)      0.100410
(10, 20)    0.159688
dtype: float64

**Comment by JackKelly** [comment]
Ah, no, please don't return that new string from the function!  That will break the caching mechanism! ;)

What I meant was, please modify the `key_for_cached_stat` function so it looks like this:

```python
    def key_for_cached_stat(self, stat_name):
        """
        Parameters
        ----------
        stat_name : str

        Returns
        -------
        key : str

        See Also
        --------
        clear_cache
        _compute_stat
        _get_stat_from_cache_or_compute
        get_cached_stat
        """
        print("BUILDING: '{}', INSTANCE: '{}'".format(self.building(), self.instance()))
        return ("building{:d}/elec/cache/meter{:d}/{:s}"
                .format(self.building(), self.instance(), stat_name))
```

(i.e. just insert the line I wrote in my last comment, and please leave all the other lines as they were)

This isn't a fix.  Just a bit of debugging investigation.  We need to get to the bottom of why either `self.building()` or `self.instance()` are returning a string and not an int.

Please run this and show us the output.

**Comment by t7reyeslua** [comment]
Ok..Thanks for the clarification. The output is this:

BUILDING: '1', INSTANCE: '5'
BUILDING: '1', INSTANCE: '6'
BUILDING: '1', INSTANCE: '7'
BUILDING: '1', INSTANCE: '8'
BUILDING: '1', INSTANCE: '9'
BUILDING: '1', INSTANCE: '11'
BUILDING: '1', INSTANCE: '12'
BUILDING: '1', INSTANCE: '13'
BUILDING: '1', INSTANCE: '14'
BUILDING: '1', INSTANCE: '15'
BUILDING: '1', INSTANCE: '16'
BUILDING: '1', INSTANCE: '17'
BUILDING: '1', INSTANCE: '18'
BUILDING: '1', INSTANCE: '19'
BUILDING: '1', INSTANCE: '(10, 20)'/home/t7/anaconda/lib/python2.7/site-packages/sklearn/metrics/metrics.py:1771: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py:787: PendingDeprecationWarning: object.__format__ with a non-empty format string is deprecated
  .format(self.building(), self.instance(), stat_name))

Traceback (most recent call last):

  File "<ipython-input-6-adbd2cdc7f12>", line 1, in <module>
    f1 = f1_score(disag_elec, elec)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/metrics.py", line 222, in f1_score
    'when_on'):

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/electric.py", line 785, in align_two_meters
    sections = master.good_sections()

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 635, in good_sections
    nodes, results_obj, loader_kwargs)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 685, in _get_stat_from_cache_or_compute
    key_for_cached_stat = self.key_for_cached_stat(results_obj.name)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 787, in key_for_cached_stat
    .format(self.building(), self.instance(), stat_name))

ValueError: Unknown format code 'd' for object of type 'str'

**Comment by JackKelly** [comment]
OK, cool, thank you.  I suspect it's the tuple that's causing the issue.  If you get a moment, please could you try running your code again with this new version of `key_for_cached_stat` (this version should print out the type name) and copy and paste the output again, thank you.

```python
    def key_for_cached_stat(self, stat_name):
        """
        Parameters
        ----------
        stat_name : str

        Returns
        -------
        key : str

        See Also
        --------
        clear_cache
        _compute_stat
        _get_stat_from_cache_or_compute
        get_cached_stat
        """
        print("BUILDING: '{}'{}, INSTANCE: '{}'{}".format(self.building(), type(self.building()), self.instance(), type(self.instance())))
        return ("building{:d}/elec/cache/meter{:d}/{:s}"
                .format(self.building(), self.instance(), stat_name))
```

thank you.

**Comment by t7reyeslua** [comment]
Thanks!...It is indeed a tuple:

```
BUILDING: '1'<type 'int'>, INSTANCE: '7'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '8'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '9'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '11'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '12'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '13'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '14'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '15'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '16'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '17'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '18'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '19'<type 'int'>
BUILDING: '1'<type 'int'>, INSTANCE: '(10, 20)'<type 'tuple'>
```

**Comment by JackKelly** [comment]
Sorry for taking a while to fix this.  I've just pushed a commit which should fix this issue.  You don't need to re-run disaggregation.  Instead just run your user code which processes the disaggregation file as it is and it should work ;)
