### ISSUE TITLE
Move docs from Sphinx to IPython notebooks

### ISSUE THREAD

**Issue by nipunreddevil** [nilmtk/nilmtk#368]
We feel that shifting all documentation to IPython notebooks would make:

1. Easier for users to download notebooks and run on their machines
2. Allow us to maintain and keep the documentation up to date with ease
3. Make it easier for users to contribute documentation. Yes, they don't have to build anything

This is a relatively straight forward task. The idea is to copy the relative bits from the documentation [up here](http://nilmtk.github.io/nilmtk/master/index.html) to the notebooks directory. We can then use nbviewer to render the IPython notebooks for us.

This task should be a good learning experience for anyone who wants to use nilmtk.

**Comment by JackKelly** [comment]
agreed 100% ;)

**Comment by JackKelly** [comment]
Two quick thoughts:

* For some hints about how to structure IPython notebooks, we could take a look at "[Probabilistic Programming & Bayesian Methods for Hackers](http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/)" (an online book written entirely as an IPython notebook).
* Ultimately, we might be able to make use of IPython's interactive widgets

**Comment by nipunreddevil** [comment]
I'll do this over this weekend. I think we have more bug reports due to old documentation, than due to genuine bugs ;)

**Comment by JackKelly** [comment]
Brilliant! Thank you ;)

**Comment by nipunreddevil** [comment]
I've updated the docs now. Do we need to add more documentation?

**Comment by JackKelly** [comment]
> I've updated the docs now

Great work :)

> Do we need to add more documentation?

I'd say we definitely need lots more docs.  I'll try to add some more when I get a chance.  Especially some docs describing the broad architecture and the main classes.

**Comment by JackKelly** [comment]
@nipunreddevil so, just so I understand, am I correct that we're still using Sphinx for our user manual?  i.e. if we want to update the docs we still need to update the source IPython notebook, then convert to RST, then run Sphinx?  If so, do you think we should, at some point, completely move our user manual out of Sphinx and have it as a 'pure' set of IPython notebooks.  i.e. so if we need to update the docs, all we have to do is update the relevant IPython notebook file?

Also, just to be clear, did you update the contents of the docs so they now use the latest NILMTK API?  Absolutely no worries if not, just trying to get a feel for what's still needed.  (I did try doing a `git diff` but all the image embedded in the IPython notebooks make diff'ing notebooks a painful process!)

**Comment by nipunreddevil** [comment]
>am I correct that we're still using Sphinx for our user manual? 

I was a bit unsure about this. So, as of now, I do as you've mentioned: convert the notebook to RST. 


> did you update the contents of the docs so they now use the latest NILMTK API?

Yes, to the best of my knowledge :) 

>(I did try doing a git diff but all the image embedded in the IPython notebooks make diff'ing notebooks a painful process!

This sure is an issue! 
There are a few alternatives:

1. https://github.com/mrocklin/pymarkdown
2. https://github.com/mobeets/jekyll-ipython-markdown
3. https://github.com/rossant/ipymd
4. https://github.com/GitbookIO/gitbook

Any thoughts?

**Comment by JackKelly** [comment]
On the topic of not being able to do meaningful diffs of notebooks... I don't think it's a huge issue.  I'd be eager to require as few dependencies as possible, even if that means having unreadable diffs for notebooks.

If and when the need to diff notebooks arises, I expect we can use a tool like http://nbdiff.org to create meaningful diffs of notebooks.

On the topic of, ultimately, moving our manual to pure IPython notebooks... I really can't decide if it's a good idea or not.  Maybe we'd miss some Sphinx features?  But, on the other hand, given that it's possible to produce books like [Probabilistic Programming & Bayesian Methods for Hackers](http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/) in pure IPython notebook, this suggests that we should be able to move a significant proportion of our manual to IPython notebooks.  And, if we did move our manual to IPython notebooks, would we move our entire docs to IPython notebooks?  I'm not sure how we'd present an HTML version of our API (docstrings etc) without Sphinx?

**Comment by JackKelly** [comment]
whilst googling, I found this: https://github.com/biocore/qiime/issues/745  (we're not the only ones playing with this!)

**Comment by nipunreddevil** [comment]
> And, if we did move our manual to IPython notebooks, would we move our entire docs to IPython notebooks? I'm not sure how we'd present an HTML version of our API (docstrings etc) without Sphinx?

This is the exact reason, I didn't expose our whole documentation as the Bayesian methods book. I think that's trivial to do. 

I am unsure if we need API docstrings. Not many people would use it. Also, with IPython, getting docs for a function is easy enough.

**Comment by JackKelly** [comment]
> I am unsure if we need API docstrings. Not many people would use it.

(just to be clear to anyone else reading this: of course, we'll have docstrings in the code, the question is whether we need to render these as HTML)... 

yeah, I've been wondering about this.  I must admit that I still google for docstrings for pandas, numpy etc.  i.e. I quite like seeing docstrings rendered as HTML (especially if those docstrings have equations in them).  But it is a bit of a development overhead to maintain them.  Anyone else have any views?!

**Comment by nipunreddevil** [comment]
Another option is to have our custom build which does the following:

1. Converts all IPython notebooks to HTML and put at an appropriate URL/directory
2. Run sphinx-apidoc to generate HTML documentation
3. Pray! 
4. Ensure that 1 and 2 somehow align well :)

**Comment by JackKelly** [comment]
I'd be keen to keep life as simple as possible and consider completely throwing away Sphinx and apidoc and doing all our docs as an IPython notebook.  I have a hunch that it wouldn't be too complex (maybe just 20 lines of code?) to produce a function which can trawl through our python files and produce nice-looking API docs in an IPython notebook.

**Comment by nipunreddevil** [comment]
I am all in for full IPython notebook based docs. I think I made an IPython notebook for each page in our documentation. So, I think we're almost there. 
Notebooks [here](https://github.com/nilmtk/nilmtk/tree/master/docs/source)

Just need the function to generate the API docs.

**Comment by JackKelly** [comment]
> Just need the function to generate the API docs.

feels like a problem someone might have already solved... (I've tried googling but haven't found anything)... I'll ask on StackOverflow...

**Comment by nipunreddevil** [comment]
Sure. Please link the question here also. I'd be interested in seeing how it is done.

**Comment by JackKelly** [comment]
http://stackoverflow.com/questions/30728660/display-api-documentation-as-an-ipython-notebook

(feel free to suggest any modifications to the question!)

**Comment by JackKelly** [comment]
one more thought: my current feeling is that the priority is to simplify the process of writing and publishing docs.  Moving to a pure IPython manual should make life as easy as possible.  As such, I think we can do without online API documentation if needs be (of course, the docstrings will still be in the code and still accessible from Python).

**Comment by nipunreddevil** [comment]
A tiny issue is that we can't add a menu system to IPython notebooks, or can we? Like, we currently have for Sphinx, where all the hyperlinks to previous page, page a level up, etc. are mentioned.

I think it is not really that important.

**Comment by JackKelly** [comment]
that's a good point.  If we render the notebooks on github then we get links up a level:

e.g.:

https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Chapter1.ipynb

(one small point: it seems the above page takes a long time to be generated by github?)

**Comment by JackKelly** [comment]
if speed proves to be an issue then perhaps we should stick with nbviewer, which also has 'up a level' links: http://nbviewer.ipython.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Chapter1.ipynb

**Comment by gjwo** [comment]
OK really stupid question, where do I view the current document set rendered i.e. not the raw html which I can see on nilmtk.github.io? or do I have to build locally?

**Comment by gjwo** [comment]
@JackKelly @nipunreddevil 
If I may be a bit contentious for a minute, I have to ask who is the documentation targeted at, and what are the knowledge prerequisites before starting? From my own viewpoint, I have a programming background and an understanding of the problem domain, but I found the learning curve severe, a less persistent person would have given up weeks back. The issue I find with the documentation is there is little in the way of overview, much of what is documented is essentially describing the code (in which case why not look at the code). The problem I find is always "Where to start looking?" I think you assume the user (or in my case naive user) already has the model of your tool kit in his head, and therefore knows which specific question to ask, and hence where to look. This is not the case!  To get to the point I am currently at - data converter working, this is the summary of the knowledge required
![image](https://cloud.githubusercontent.com/assets/12109990/8059322/4e1e3980-0eb7-11e5-8845-4573267ce723.png)

None of the above however gives an understanding of the tool kit, What is needed are some diagrams which show the flow through the tool kit (I know there is one, but the next level of detail is needed). Also  some explanation of the key data-structures and the typical things that would be done to these, plus some "how do I ...?" questions and answers FAQ or similar. Examples in notebooks are also good, but as I have found, without the underlying understanding of the model it is not possible to work out if a call is appropriate or not (meters versus meter groups for example)

If I had a better understanding I would help with this, however all I can do currently is act as a guinea pig, and offer constructive criticism.

**Comment by JackKelly** [comment]
Hi Graham,

I totally agree with all your points and I'm frankly in awe at your ability to figure out lots of stuff about NILMTK which isn't yet documented!  And all your suggestions are spot-on.

We'd dearly love for NILMTK's documentation to be as comprehensive as you'd like it to be.

Just to give a bit of background (much of which you've probably inferred already!). NILMTK started life back around December 2013 as a collaboration between three PhD students: Nipun, Oli and me (or was Oli a postdoc by then, I don't remember?!).  We set out to build an *academic* tool.  In NILM research it was then (and is still now) very hard to compare any pair of NILM papers because each researcher uses a different dataset, different metrics, cherry-picks appliances, never releases any code etc.  The end result is that paper A might report 80% accuracy and paper B might report 90% accuracy but it is in no way possibly to infer from this that algorithm B is better than algorithm A (perhaps B only used a day of data across 4 cherry-picked appliances but paper A used 5 years of data across 20 appliances, for example)  So we hoped that we could help things along by writing an open source academic tool (and I think NILMTK has helped a bit... certainly in terms of developing a common format for datasets).

Fast-forward to today and NILMTK is still very much an *academic* tool rather than a user-facing tool.  So, at the moment, our main target audience is still largely academics who are working in NILM research. We'd love to have a solid chunk of time to sit down and clean up the NILMTK code and write gorgeous documentation and a comprehensive testing suite.  But that stuff does take a *lot* of time.  It's work that we fully intend to do as and when we get the time, but time is short at the moment.

Looking to the future, it's possible that I might get a postdoc position which would allow me to spend a good chunk of time on NILMTK.  And I'd certainly hope to clean up the docs.  And, ultimately, to make NILMTK into a more user-facing tool.  (one of the main reasons I got into NILM research in the beginning was to help people to save energy, and creating a user-facing NILM tool seems a good way to do that!)

Sorry this was a long reply but I totally agree with all your points and we are working towards making the documentation as good as you'd like.  But it does take time.  In a way, open source dev is quite frustrating because of course we'd love to make NILMTK gorgeous in every way we can, but we are really constrained in the amount of time we can spend on it.  One tension is, of course, that academics get no direct credit for spending time on open source projects (although that might be changing, slowly).  At the end of the day, academics are still measured primarily on how many papers we write, not on how much code we write.  I (and many other people) think this situation is horrible but it is the state of the game at the moment.  (Open science is a fascinating topic and a whole other rant!...)  So, ironically, if I want to increase my chances of being able to get a research fellowship after my PhD (to work on NILMTK), I need to spend the remainder of my PhD writing *papers* not code!

**Comment by JackKelly** [comment]
(although, of course, I fully intend to spend as much time as possible supporting NILMTK and writing NILMTK code and docs!)

**Comment by gjwo** [comment]
Hi Jack,
Understood! However I may be able to help as I have lots of time, and this is an "interesting" topic. I am not yet playing to my strengths, which major on the analytical not modern development environments. Once I can get my head around this (and I will) I can help put it in terms others can understand. The problem with understanding a toolset or library like this, is it is missing the flows of control, which is why I have been working through the demos. 

I could have carried on with my own java code, but I reasoned, that much of this stuff ought to have been done before, and indeed it has been. Much of my time previously was spent on writing classes to handle the data flexibly, which the whole pandas thing does much better. Having gone through many of the academic papers, the major techniques are clear (A number of them I had inferred from playing with my own data, but without the academic rigour). I don't see the point of re-inventing the wheel.
 
I don't need finished documentation, scans of scribbled notes or photos of whiteboards would help enormously, which I could them play back in the form of better documentation, once I am sure I have understood them, with the help of a few questions being answered.

If you and Nipun are up for this, I would suggest we open a "Beginner's Questions" issue, or find some other way of stopping my ramblings in off topic places.

**Comment by nipunreddevil** [comment]
Graham,
Like Jack, I fully agree with your points. 

>I would suggest we open a "Beginner's Questions" issue, or find some other way of stopping my ramblings in off topic places.

I think hosting a FAQ/Beginner's guide would be good. It would be great if you could keep pushing your notes to these guides. For instance, all the issues you've faced on Windows along with their solutions could go on Windows installation instructions. Other issues like the errors you faced while writing your metadata could go in some kind of "errors you may face" document. 

Also, now that you've got a good understanding about nilmtk (unfortunately, the hard way), it would be great if you could tell us the exact things which would have made your life easier. I think this could be a good starting step as opposed to waiting for the day when we'll be able to write everything very comprehensively. I think at my level, I faced this challenge of not knowing what all things users would find useful in the documentation. 

Great to have your feedback on nilmtk :)

**Comment by oliparson** [comment]
Hi guys,

Sorry for my lack of input, I've been following the discussion but haven't had the chance to respond until now. I agree that putting as much documentation in ipython notebooks (cookbook style) is the way to go. I think notebooks are pretty well understood now, and it's nice that people might be able to contribute without having to understand a documentation-specific format. With regard to the class and function documentation, I really don't mind what we use so long as it builds automatically from docstrings. In this respect, sticking with sphinx might be the easiest thing to do.

With regard to deciding what documentation to write, I think it would be useful to have a Google Hangout with the four us (Jack, Nipun, Graham and myself) to brainstorm ideas and plan a structure. Writing docs isn't the most thrilling of tasks, so I'd hope we can divide it roughly equally between the four of us.

Would you be up for this @gjwo ?

**Comment by gjwo** [comment]
@oliparson - Yes I would
@nipunreddevil - I don't yet have a good understanding, I have only converted a set of data and done some basic data interrogation, I have not yet touched training or dissagregation. I am happy to help with what the probelms were, while I can still remember.

All, I think Oli's suggestion is a good one to develop an approach, as I don't think github issues have enough structure toe help users find more general help. I think we will need the following types of things:
1. Answers to specific technical problems & technical bugs: use issues
2. General introduction to the toolset: some kind of structured document
3. Developers overview: diagrams, typical control flows, data structure explanations
4. FAQ: Q&A format
5. How to / Cook book / Demos: Annotated iPython notebooks

**Comment by gjwo** [comment]
We might also need a section on techniques for analysing data for example
* Using data signatures/fingerprints (combining apparent & reactive data)
* Daily data stacking, to strengthen fingerprints
* Feature analysis
* Different disaggregation algorithms and their pros and cons
* Graphing

**Comment by nipunreddevil** [comment]
@JackKelly , @gjwo, @oliparson Does tomorrow morning/afternoon UK time work for a discussion? I am away this Friday.

**Comment by oliparson** [comment]
This week is a bit tricky for me. Any chance we could do next week either Tuesday (16th) or Friday (19th)?

**Comment by gjwo** [comment]
All OK with me

**Comment by nipunreddevil** [comment]
Both 16th and 19th work for me.

**Comment by nipunreddevil** [comment]
Both 16th and 19th work for me.

**Comment by nipunreddevil** [comment]
Both 16th and 19th work for me.

**Comment by oliparson** [comment]
We get it Nipun ;)

**Comment by nipunreddevil** [comment]
I am sorry message went multiple times :)

**Comment by JackKelly** [comment]
I can do any time on the 19th.  How does 10:00 BST (UTC+1) work for everyone?

@gjwo I think your two lists of documentation are spot on.

It had occurred to me that I should try to write some more documentation in time for the NILMTK afternoon on 9th July in London (part of the [nilm.eu workshop](http://www.nilm.eu)).  Not sure if that will happen or not though!

**Comment by oliparson** [comment]
Good for me :)

**Comment by gjwo** [comment]
This is what I think a "FAQ" or "How to" answer should look like as a notebook, from https://github.com/nilmtk/nilmtk/issues/405
**Question**
My data contains two measurements per second, apparent & reactive power, I would like to be able to view them as two lines on the same graph (with the axes adjusted appropriately), and to be able to change the time period of the graph to be able to zoom in and out on features. Can this be done? are there any examples of how to do it? My data is available here https://github.com/gjwo/nilm_gjw_data/blob/master/HDF5/nilm_gjw_data.hdf5

**Answer**
see the following notebook
https://github.com/gjwo/nilm_gjw_data/blob/master/notebooks/graphing_two_metrics.ipynb

**Comment by nipunreddevil** [comment]
@gjwo Thanks ton for this!

@JackKelly, @oliparson : I've just created a nilmtk [cookbook](https://github.com/nilmtk/nilmtk/blob/master/cookbook.md). 

I think it would be great if this becomes community driven like [Pandas cookbook](http://pandas.pydata.org/pandas-docs/stable/cookbook.html) is. I've contributed a few articles to the cookbook.

**Comment by gjwo** [comment]
@oliparson @nipunreddevil @JackKelly What are the arrangements for the hangout tomorrow?
As further input, I think I have worked out what is holding me back, it's an understanding of the data structures, how they fit together, what is stored in the HDF5 files etc. I have stared at the code, and it's still not obvious, I guess because I am used to languages that are explicit about their data. Although it is documented in method definitions what the parameters are, I couldn't easily find what is stored in the classes, files etc, I guess for people who use Python a lot, this isn't a worry, but it is driving me nuts.

**Comment by nipunreddevil** [comment]
10 AM BST, 2:30 PM IST 
@JackKelly : Can you please initiate the hangout?

**Comment by gjwo** [comment]
More input for tomorrow, below is the mindmap that I wish I had had 3 or more weeks ago to get an overview of the structure of the toolkit.this doesn't explain how to use it (as covered by some of @nipunreddevil demos) or how to build it, but it has helped me understand it. And might help others see the wood for the trees. I have also included some questions, because there are still some seriously large gaps in my understanding (although I am now down to clearly defined areas of doubt and uncertainty. :smiley:  

![nilmtk](https://cloud.githubusercontent.com/assets/12109990/8234455/f46021fa-15d3-11e5-8cc5-ccce98887327.jpeg)

**Comment by nipunreddevil** [comment]
@gjwo : The mind map looks fantastic! Thanks for sharing this!

**Comment by gjwo** [comment]
@nipunreddevil Thanks, please feel free to criticise and correct as appropriate.

**Comment by JackKelly** [comment]
sure, I'll start the hangout at 1000 BST tomorrow.

**Comment by JackKelly** [comment]
if it's OK, I'll need to finish by 1100 BST to go to another meeting.

**Comment by oliparson** [comment]
Google doc summarising documentation to be written:
https://docs.google.com/document/d/1JvBisEifgrOaFoXnPc3VHA8M84kbH3DPeLiVyD-ORqM/edit?usp=sharing

**Comment by JackKelly** [comment]
really sorry, today is slipping away from me... I'll get my TODO items done tomorrow or early next week

**Comment by JackKelly** [comment]
so, I'm working on moving our docs from Sphinx to IPython notebook today.

Two issues:

1.  Some of our new docs pages are pretty much completely devoid of any Python code (e.g. our 'contributing' page).  These are currently done as IPython notebooks where every cell in a markdown cell.  It occurred to me that we could do these pages as `.md` markdown files.  These would be rendered by github, and could be edited in a text editor.  I did experiment with this but I didn't like that I had to run `pandoc Contribute.md -o Contribute.html` every time I wanted to check the formatting was correct.  IPython notebooks like it really easy to check that markdown renders correctly.  And, of course, it renders maths well.  So I'd suggest that we stick to using IPython notebooks, even for pages without any Python code.

A third alternative would be to store the 'pure' markdown manual pages on the wiki, which would make them super-easy for folks to edit.  But it might be a bit ugly to have our manual scattered between the wiki and IPython notebooks.

2. I'm really undecided as to whether the manual IPython notebooks should go into `nilmtk/notebooks/manual` or in `nilmtk/docs/manual`.  I suppose it doesn't really matter as long as we provide an obvious 'way in' in the README.  Any thoughts?

I've also moved some relevant content from the NILMTK wiki into the new notebooks.  And deleted a few redundant wiki pages.  And I figure I might as well update the README with the manual table of contents, if that's OK @oliparson ?

**Comment by JackKelly** [comment]
regarding issue 1) in my comment above, hmm, I *do* think the changelog should be a plain text file.  Which also informs issue 2), because the manual no longer is purely ipynb files.  So I think I'm leaning towards:

1) having the majority of our docs as ipython notebook files, but allowing some .md files.
2) putting the manual in `nilmtk/docs/manual`.  I suspect this is where users would first look.  And it no longer makes sense to put the manual in `nilmtk/notebooks/manual` if it isn't pure notebooks.

thoughts?

**Comment by JackKelly** [comment]
another thing that's on my mind is the overlap between the `README.md` file and the Introduction in the manual.  I'm learning towards the view that `README.md` should contain everything in the 'Introduction' section in our google doc.  I've moved the content from `docs/source/about.rst` into the README (although I haven't committed yet)

**Comment by JackKelly** [comment]
OK, I'll close this issue because we have finished doing the original task in this issue (moving docs from Sphinx to IPython).  The docs layout feels more sane now, and much easier to maintain, but there are still large gaps.  There are several other issues about adding new docs so I'll consolidate and update those...

Of course, if you have concerns or thoughts about any of the decisions I've made when moving docs to IPython then please comment on this issue...

**Comment by JackKelly** [comment]
I'm using #196 to keep track of the new docs we need to write at some point

**Comment by nipunreddevil** [comment]
https://github.com/aaren/notedown looks interesting.

**Comment by JackKelly** [comment]
That does look interesting. Personally, I'm happy with the system we have
now (ie a mixture of iPython notebooks and pure markdown files).  I'd be
reluctant to add another dependency and another step unless there's a
concrete reason to.
