### ISSUE TITLE
Request for CSV format data to aid understanding  of how toolkit operates 

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#391]
@oliparson 
As indicated on https://github.com/nilmtk/nilmtk/issues/389, please can you let me have a smallish sample of .csv files to help me understand how the toolkit works with such files, and some ipython snippets of how to use them.

**Comment by JackKelly** [comment]
A quick bit of background: there are two broad ways to get CSV into NILMTK:

1. Convert CSV to HDF5 and then use HDF5.
2. Use the `CSVDataStore` to directly load CSV.

There are several examples of the former approach (e.g. take a look at the [REDD dataset](http://redd.csail.mit.edu/) (which is CSV) and [the REDD converter](https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters/redd)).  And [the tutorial on NILM Metadata](http://nilm-metadata.readthedocs.org/en/latest/tutorial.html) is based on REDD.

**Comment by gjwo** [comment]
I am going to produce a set of metadata to go with my data, what is the directory structure for data and metadata, and where does that tree sit relative to the toolkit directories, or does this not matter?

**Comment by JackKelly** [comment]
The following post assumes you're going down the route of converting your CSV files to HDF5, rather than using `CSVDataStore`.  Going down the `CSVDataStore` route is probably best if you regularly update your CSV files.

> what is the directory structure for data and metadata

All the `.yaml` files should go in single directory (which we usually call `metadata`).  The NILM Metadata project includes a [`convert_yaml_to_hdf5()` utility](https://github.com/nilmtk/nilm_metadata/blob/master/nilm_metadata/convert_yaml_to_hdf5.py#L15).

NILMTK doesn't care what structure you use for your source CSV files because your converter code will convert it to a NILMTK's standard HDF5 format ([here are the docs for how to do that](http://nilmtk.github.io/nilmtk/master/writing_a_dataset_converter.html)).  I'd suggest using the [REDD converter](https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters/redd) as a template and modifying where necessary (e.g. you'll need to tell Pandas that your first column isn't a UNIX timestamp).

**Comment by gjwo** [comment]
If I am going down the CSVDataStore route, wihich seems sensible as the data could be pulled from my meter weekly, do I not sill need to do something to import and process the .yaml files?

**Comment by oliparson** [comment]
Here's a zip of an [example](https://drive.google.com/file/d/0Bw-3bVfLyUdMOHdDamJUV1JvY0k/view?usp=sharing) `CSVDataStore` for 1 house which should help get you started. Once extracted, you should be able to load it using `ds = DataSet('one_house', format='CSV')`. I should warn you though that we haven't optimised the reading of CSVs, so random access will be slow. You'll get the best experience by downloading an existing data set and converting it to HDF5 using one of the `dataset_converters`.

**Comment by oliparson** [comment]
I also made a few changes to CSVDataStore so make sure you pull the most recent changes.

**Comment by gjwo** [comment]
@oliparson  
Where does the onehouse folder need to go? under nilmtk/data?

**Comment by oliparson** [comment]
You need to give the full path to the directory, e.g. `ds = DataSet('C:/data/one_house', format='CSV')`

**Comment by gjwo** [comment]
Thanks, and thanks for the data, I should be able to see what is going on now

**Comment by gjwo** [comment]
OK my thoughts  on how to proceed, comments welcome
![image](https://cloud.githubusercontent.com/assets/12109990/7839855/89c607e0-048c-11e5-8011-04044157d788.png)

my current meter file

ED01013:
  model: ED01013
  manufacturer: Onzo Ltd
  manufacturer_url: http://www.onzo.com/
  description: Multifunction whole house meter and home display, 
#    given the different sample rates and cumulative energy mixed, phase one treat the meter
#    as having only 2 measurements power real fine and power reactive, comment out the rest
  sample_period: 1 # the interval between samples. In seconds.
  max_sample_period: 300 # Max allowable interval between samples. Seconds.
  measurements:
#  - physical_quantity: cumulative energy   #energy low res - cumulative energy use every 35 minutes approximately
#    type: active   # active (real power), reactive or apparent?
#    upper_limit: 10000000
#    lower_limit: 0
#  - physical_quantity: cumulative energy   #energy high res - cumulative energy use every 10 minutes approximately
#    type: active   # active (real power), reactive or apparent?
#    upper_limit: 10000000
#    lower_limit: 0
#  - physical_quantity: power   #power real standard - power granularity < 30 Seconds
#    type: apparent   # active (real power), reactive or apparent?
#    upper_limit: 10000
#    lower_limit: 0
  - physical_quantity: power   #power real fine - power granularity  1 Second (no data if no change)
    type: apparent   # active (real power), reactive or apparent?
    upper_limit: 10000
    lower_limit: 0
  - physical_quantity: power   #power reactive standard granularity  1 Second (no data if no change)
    type: reactive   
    upper_limit: 10000
    lower_limit: -10000

**Comment by gjwo** [comment]
not sure why # at the start of the line causes issues with fonts!

**Comment by nipunreddevil** [comment]
In Markdown syntax, # refers to heading.

**Comment by gjwo** [comment]
that's a bit inconvenient for comments in yaml or python :-)

**Comment by nipunreddevil** [comment]
@gjwo : I've updated your comment. Please have a look above. Markdown allows code snippets.

**Comment by gjwo** [comment]
Thanks Nipun, I made a slight correction to where the code started, now I just need to work out why pasting from Microsoft Onenote always end up as an image file rather than text.
Does the meter file look OK to you?

**Comment by oliparson** [comment]
Hi Graham, this approach looks good to me. Just wanted to check your converter is going to do Onzo CSV -> NILMTK HDF5 rather than Onzo CSV -> NILMTK CSV. The HDF5 format is much faster and better tested for use with NILMTK, while the CSV format was mainly designed to allow NILMTK data to be exported for use by environments.

I'd recommend you look into [pandas](http://pandas.pydata.org/) for reading CSVs into memory and joining them. [DataFrame.merge](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) should do exactly what your after.

**Comment by gjwo** [comment]
Hi Oli,
Yes I am planning to go to HDF5, I am in the process of writing the converter at the moment, I have also written most of the metatdata (ground floor done). I have already looked into pandas I bought the book "Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython" by Wes McKinney which looks pretty good. Thanks for the hints, I had already spotted pandas.read_csv in other converters but the Dataframe.merge is timely as that is the stage I should reach today. I have to merge data vertically (combining 2 time correlated CSV files to add the apparent & reactive power columns to the same structure) and horizontally   (to combine time sequenced data column merged dumps together). I will close this issue and create a new one on writing a converter if I get stuck.
