### ISSUE TITLE
Consider keeping cache in separate file

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#402]
At the moment, we modify the main dataset HDF5 file to store cached statistics.  This has the advantage that the cache is kept with the data.  But it has several disadvantages:
- Sometimes the HDF5 can become corrupted (e.g. in #328)
- It slightly complicates our unit tests (because we need to replace modified test files with originals)

So perhaps we should consider keeping the cache in a separate file (maybe even keeping it in the OS temporary directory)?

**Comment by PMeira** [comment]
I think this is a great idea. Ideally the datasets should be open as read-only.

**Comment by levaphenyl** [comment]
Opening datastores in a read-only mode would allow parallel uses of the same resource.

**Comment by levaphenyl** [comment]
@JackKelly @PMeira I just opened a [PR](https://github.com/nilmtk/nilmtk/pull/901) to fix this ticket.
As the issue dates from 5 years ago, can you confirm the PR addresses the original problem?

Your review will be highly appreciated!

**Comment by PMeira** [comment]
@levaphenyl We might need to tweak it a bit (that's why I reopened this) but it does cover the main aspects.
(sidenote: Jack effectively left the project long ago)

**Comment by levaphenyl** [comment]
@PMeira What tweaks do you imagine? 
Thanks for the sidenote, I won't expect an answer from Jack in the future :).

**Comment by PMeira** [comment]
> What tweaks do you imagine?

@levaphenyl One issue I was going to mention you handled in f97bf2cbc2fb013f9c854157de3b960ed5279c01 (I didn't know it would cause issues with number of open files, though). 

The other is that, ideally, we should probably a way to keep the cache too, in a separate file per dataset.
But... due to the limitations of HDF5 as exposed in Python, more explicitly, it's not built for parallel processes using the same file in the default distributions (that's what causes the corruption and other weird issues), we should handle that after investigating an alternative better. 

That is, your solution seems ideal in face of the limitations right now. If you prefer, we can close this old ticket and open a more specific one (I just didn't want to forget about it).

**Comment by levaphenyl** [comment]
Thank you for the explanation!

I agree the cache should be reusable instead of regenerated each time. The issue seems linked to the way we store data in NILMTK, so its impact goes beyond the statistics.
Closing this ticket and opening a new specific one seems the best way to go :).
