### ISSUE TITLE
How to identify the individual circuit belong to which power main?

### ISSUE THREAD

**Issue by narrowview** [nilmtk/nilmtk#412]
I get the low frequency power data in the form of dat,not csv or hdf5.
I want to identify the individual circuit belong to which power main.And I read part of NILMTK code,but can't understand how the NILMTK identifies which main the circuit belongs to.
So I have three questions.
1.How to identify the individual circuit belong to which power main?
2.Is it the reason of format of data?
3.Why the sum of two power mains is not equal to the sum of other,in low frequency power data?

**Comment by JackKelly** [comment]
Hello and welcome to the NILMTK issue queue!

I'm really sorry but I'm not sure I understand what you mean by 'I want to identify the individual circuit belong to which power main'.  Do you mean that you have aggregate power data (recording the whole home's power demand) and you want to disaggregate it into appliance-by-appliance power demand?

Regarding your other questions:

'Is it the reason of format of data?'  If you want documentation of the data format then please see: http://nilmtk.github.io/nilmtk/master/writing_a_dataset_converter.html

'Why the sum of two power mains is not equal to the sum of other,in low frequency power data?'.  Do you mean 'why is the sum of the submeters not equal to the aggregate'?  This is typically because houses rarely are able to sub meter every appliance.  There are also issues to do with measurement error and the differences between apparent, active and reactive power.

**Comment by narrowview** [comment]
Thank you very much.Because I'm not good at English,so my expression may be not very accurate.
I have two ideas about disaggregate the data.The first is disaggregating the sum of two mains.And the second is disaggregating two mains individual.My first question above is about the second one.
My first question is that there are two mains and many appliances in a house,and how to know any appliance belongs to which main.
And I have another question.For  appliance which has little power change,how to know it is turning on or off?

**Comment by JackKelly** [comment]
Nilmtk doesn't currently have any code for automatically figuring out which mains split each submeter is connected to. We have discussed this in the past but I don't think we implemented anything. 

Nilmtk's metadata schema can express which mains split each submeter is connected to, if this mapping is known. 

If an appliance doesn't change its power demand then it is invisible to event based nilm.  If it does change its power demand but the changes and small relative to the noise then it will also be invisible to event based nilm.

**Comment by nipunreddevil** [comment]
Maybe a past work of mine may be pertinent-
https://www.researchgate.net/publication/257527705_INDiC_Improved_Non-Intrusive_load_monitoring_using_load_Division_and_Calibration

**Comment by gjwo** [comment]
Thanks Nipun, I will read that over the weekend.

**Comment by narrowview** [comment]
Thanks Nipun and Jack.I will read the paper for more details.
