### ISSUE TITLE
More implementations of disaggregation

### ISSUE THREAD

**Issue by meteorjs3000** [nilmtk/nilmtk#457]
Are there more implementations of disaggregation algorithms that we can play with apart from the ones that come with nilmtk (hart85, co, fhmm_exact)?

I'm particularly interested in how the [neural net method](https://github.com/JackKelly/neuralnilm) can be implemented in nilmtk. Does that sound possible?

**Comment by oliparson** [comment]
I think Jack's neuralnilm code plays nicely with NILMTK, see his notebooks for more details. This one in particular might get you started:
https://github.com/JackKelly/neuralnilm/blob/master/notebooks/Neural%20NILM%20test.ipynb

We're actually having a discussion about how best to get two existing algorithms into NILMTK this Friday if you'd like to join us:
https://plus.google.com/events/cr8v2r2uh2lgn16s10jjq5jv83k
see my blog post for more details:
http://blog.oliverparson.co.uk/2015/11/hangout-on-air-nilmtk-algorithm.html

**Comment by JackKelly** [comment]
Hi @meteorjs3000,

Very glad to hear you're interested in using neural nets for NILM :)  It is a fun and exciting area of research.

The short answer is that there is not yet an easy, off-the-shelf way to use my neural net code to do disaggregation.  My Neural NILM code base is *very* "researchy".  Which is to say it has virtually no documentation and isn't really designed with 'end users' in mind.  Rather it's just the code base that I use for running my experiments.  And I don't think anyone in the community is yet confident of which neural net architecture will win out in the end; hence our focus is very much on writing code which allows us to quickly tweak the network architecture and hyperparameters and experiment rather than on building a solid disaggregation tool.

Also, I am now very much in the 'write up' phase of my PhD and so I won't be able to work on any more code until after my PhD thesis is finished (some time early 2016) I'm afraid.  You are, of course, more than welcome to tinker with the Neural NILM code base but I'm afraid I won't be able to give much support because I need to focus on my PhD write up.

That said, I am excited about the prospect of using neural nets to do NILM.  Experiments done so far show promise for the technique, although we're a long way from building a solid disaggregation tool that can be used at scale.  My aim is certainly to release open source code which will make it nice and easy to use neural nets to do NILM.  But that code is a while away, I'm afraid.  Others might get there first, of course!

Thanks,
Jack

**Comment by JackKelly** [comment]
I'll close this issue for now.  Please do re-open if necessary.
