### ISSUE TITLE
F1 score for regression?

### ISSUE THREAD

**Issue by wederer** [nilmtk/nilmtk#524]
NILMTK provides a F1 score to measure performance however I am having trouble wrapping my head around a F1 score used for a regression problem? 

How exactly are you calculating this measure? I took a look at the code, but it didn't get any clearer to be honest.

This might be a huge misunderstanding on my part, but I would be grateful if anybody could give me some input on this.

Thanks

**Comment by oliparson** [comment]
The precision, recall, and F1 scores are used to determine whether an appliance was correctly detected as being 'on' within an interval of time rather than estimating the power demand. To do so, the metric applies a threshold to the estimated and actual power demand, above which the appliance is assumed to be on, and below which the appliance is estimated to be off. Does this answer your question?

**Comment by wederer** [comment]
Wow that was fast.

Yes that does clear things up, I also just now found this treshold.
`
DEFAULT_ON_POWER_THRESHOLD = 10`

So anything over 10 watts is considered to be on, correct?

**Comment by oliparson** [comment]
Yup. Obviously this threshold is pretty arbitrary, so feel free to tune it in your own experiments!

**Comment by wederer** [comment]
Thank you very much!
