### ISSUE TITLE
Creating a conda NILMTK package

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#554]
Hi NILMTK community,
We strive to make NILMTK easy to install and work with. We've come to realise that unless one is developing NILMTK, one does not need to go through passing tests, bleeding-edge NILMTK versions. The best solution might be to package NILMTK and NILM_Metadata using conda-forge. We would need some volunteers to help in the packaging process! 

I believe once a conda-forge recipe has been created, we, the NILMTK developers can focus on the more important issues that NILMTK was designed to address.

cc @JackKelly , @oliparson

**Comment by nipunbatra** [comment]
Here was an unsuccessful attempt at creating a conda forge recipe for NILM_Metadata
https://github.com/conda-forge/staged-recipes/pull/2665

**Comment by PMeira** [comment]
I'm experimenting with conda packages. Right now I'm using my own channel with minimal recipes, but if everything works we can move to the official NILMTK channel or try to push to conda-forge.

I built Windows and Linux (x64) packages for `nilmtk`, `nilm-metadata` and `hmmlearn`. In most scenarios it should be enough to install them on the activated environment with:

```conda install -c pmeira nilmtk```

Still need to test on multiple Linux distributions and investigate the situation with MacOS.

**Comment by PMeira** [comment]
Quick update: it worked fine with openSUSE and Ubuntu (x64). Since it looks like we still need to fix some issues related with Pandas 0.23, right now I recommend installing it with:
```
conda install -c pmeira nilmtk pandas==0.22
```

For MacOS, I'll look into integrating the conda-build process in TravisCI (or something like it).

**Comment by nipunbatra** [comment]
Great work, @PMeira 

Having something like `conda install -c pmeira nilmtk pandas==0.22` would make life super simple!

Any chance you documented the process for creating the conda package? I think it would be useful for future releases.

Given that it works with openSUSE and Ubuntu, it should likely work well with OSX too.

Yeah, integrating it with TravisCI would be great.

I think in the .travis.yml files, only changing the following lines should suffice:

```
install:
  # create and activate env using NILMTK's environment.yml
  - conda env create 
  - source activate nilmtk-env
```

to:

```
conda install -c pmeira nilmtk pandas==0.22
```

**Comment by PMeira** [comment]
@nipunbatra The main difficulty is building the binary package for `hmmlearn`, as it needs to be built in all OSs separately. Both `nilm-metadata` and `nilmtk` itself are plain Python so we just need to list the dependencies correctly. 

> Any chance you documented the process for creating the conda package? I think it would be useful for future releases.

I'll document it in detail in the future, right now there is not much to it. I need to tweak the conda recipes and try to automate the building process as much as possible so we can get recent builds as soon as possible -- when we get to a stable release that won't be as important though.

Overall, you just need the recipes and, for each OS, you need a valid environment to run `conda-build`:
- Linux is the easiest target, `conda` now provides the compiler (easier to make it work on multiple distros)
- Windows is finicky -- `conda-build` gets confused easily so I used a VM with a minimum installation
- Apparently you'd just need to install the SDK on MacOS, but I haven't been able to test it (not a lot of Macs around here)

After building, you can upload with the anaconda.org client or via browser.

> Yeah, integrating it with TravisCI would be great.

I was thinking in using it to build and push the packages somewhere. Some people use it for that with success (not always for conda). 
Using `conda-forge` to build the packages should simplify some aspects but the main issue is `hmmlearn`, i.e., I'm not sure what's the best way to handle it. I can try it later though, for now I'll just test on my channel.

By the way, I noticed there is a NILMTK user in anaconda.org already -- if you guys have control over it, we could consider using it instead of my personal channel, if we can't go the conda-forge route.

**Comment by nipunbatra** [comment]
>By the way, I noticed there is a NILMTK user in anaconda.org already -- if you guys have control over it, we could consider using it instead of my personal channel, if we can't go the conda-forge route.

I think I would have probably created the NILMTK user. Let me see if I can delete it/share the credentials.

**Comment by PMeira** [comment]
> I think I would have probably created the NILMTK user. Let me see if I can delete it/share the credentials.

@nipunbatra Hey, did you manage to find out something about this?

**Comment by nipunbatra** [comment]
@PMeira Yes, I managed to find that I own the nilmtk username. Can you please send me your preferred email id, and I'll change the login to your email id.

**Comment by PMeira** [comment]
@nipunbatra Nice! My account there (anaconda.org) is using pmeira at ieee.org. If the NILMTK account is set up as an organization account, it should allow multiple admin accounts.

**Comment by ayushp20** [comment]
@nipunbatra The changes made to the build recipe for nilm_metadata (pull request #35) allows for a successful installation of nilmtk on Windows and Linux. MacOS is yet to be checked but it's likely that the installation will work there as well. The run requirements in the meta.yaml still require pandas=0.22 and hmmlearn. We can work towards migrating to pandas 0.25 and pomegranate 0.11 to fix those issues.
`conda install -c nilmtk nilmtk`  

This should close #116 #731 #728
