### ISSUE TITLE
number of mains to use

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#586]
labels.dat

1 mains
2 mains
3 oven
4 oven
5 refrigerator
6 dishwaser
7 kitchen_outlets
8 kitchen_outlets
9 lighting
...
In the labels.dat, does 1 and 2 have to be mains?  Can I use only one mains and 2 for appliance?
Thank you very much.

**Comment by nipunbatra** [comment]
I don't get your second question

On 6 Jul 2017 21:41, "suni9915" <notifications@github.com> wrote:

labels.dat

1 mains
2 mains
3 oven
4 oven
5 refrigerator
6 dishwaser
7 kitchen_outlets
8 kitchen_outlets
9 lighting
...
In the labels.dat, does 1 and 2 have to be mains? Can I use only one mains
and 2 for appliance?
Thank you very much.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nilmtk/nilmtk/issues/586>, or mute the thread
