### ISSUE TITLE
Greend converter - yaml files

### ISSUE THREAD

**Issue by MartinNeighbours** [nilmtk/nilmtk#619]
I'm new to this and have downloaded the greend dataset and am working on importing it.  I believe I have a couple of code fixes for converting the data and plotting "good data" that I will happily post.  These will resolve some of the old issues that some users have posted.

The yaml files seem to be a bit confused.
- firstly it seems sensible to rename them from 1-8 to ensure consistency with the approach used in the converter.  Otherwise I've found that the metadata gets allocated to the wrong building

- secondly and more significantly, building0 and building1 appear to be the same thing and both have the same instance id of 1.  This results in the metadata being mis-matched with the buildings as this appears to rely on instance id being in the same order as the buildings in the HDF file.  As a result the building1 metadata gets overwritten with building2 and so on

I've also noticed that the appliances in the yaml file are inconsistent with the 22/5/14 report which lists 9 houses and the appliances in each.  Is there a correct version of the files?

Many thanks

Martin

**Comment by PMeira** [comment]
> - firstly it seems sensible to rename them from 1-8 to ensure consistency with the approach used in the converter. Otherwise I've found that the metadata gets allocated to the wrong building

Not sure what happened with the naming and numbering conventions here but it's probably what's caused the confusion about House#1. I rename the files to start from 1, since the original_name is preserved inside them.

> - secondly and more significantly, building0 and building1 appear to be the same thing and both have the same instance id of 1. This results in the metadata being mis-matched with the buildings as this appears to rely on instance id being in the same order as the buildings in the HDF file. As a result the building1 metadata gets overwritten with building2 and so on

I rewrote the YAML for House#1 based on the [paper](https://arxiv.org/abs/1405.3100), but it doesn't contain all information such as building details and appliance models.

Another issue I found was that `building7.yaml` had no data about the appliances and listed only 3 meters. The paper and CSVs list 9 meters, so I rewrote it to match it.

> I've also noticed that the appliances in the yaml file are inconsistent with the 22/5/14 report which lists 9 houses and the appliances in each. Is there a correct version of the files?

I couldn't find the missing house either. The newest file seems to be `GREEND_0-2_300615.zip` and it contains 8 buildings.

@MartinNeighbours Thanks for the report, it helped a lot.

Since this seems to be handled now, I'm closing this in favor of the more general #680.

**Comment by pilillo** [comment]
Hi guys, do not want to re-open the topic and I have not been active in this community for several years.
I regularly get emails on this topic and generally just reply them directly.

The paper available on Arxiv at https://arxiv.org/pdf/1405.3100.pdf is a preprint.
You should always refer to the actual conference version, available on ieee xplore and http://web.diegm.uniud.it/tonello/PAPERS/CONFERENCES/SGC2014_2.pdf 

As visible there is a small difference in the house metadata. We had to remove house#1 that you see in the arxiv paper,  the "detached house with 2 floors in Villach (AT). The residents are 3 university students, having irregular working-like days." The reason was that the platform was regularly disconnecting from the network, getting off for periods or having bad coverage. I have never understood if it was mainly the inhabitants just switching the raspberry off or some other reason.

Anyways, the list is:

* House 0 a detached house with 2 floors in Spittal an der Drau (AT). The residents are a retired couple, spending most of time at home.
* House 1 an apartment with 1 floor in Klagenfurt (AT). The residents are a young couple, spending most of daylight time at work during weekdays, mostly being at home in evenings and weekend.
* House 2 a detached house with 2 floors in Spittal an der Drau (AT). The residents are a mature couple (1 housewife and 1 employed) and an employed adult son (28 years).
* House 3 a detached house with 2 floors in Klagenfurt (AT). The residents are a mature couple (1 working parttime and 1 full time), living with two young kids.
* House 4 an apartment with 2 floors in Udine (IT). The residents are a young couple, spending most of daylight time at work during weekdays, although being at home in evenings and weekend.
* House 5 a detached house with 2 floors in Colloredo di Prato (IT). The residents are a mature couple (1 housewife and 1 employed) and an employed adult son (30 years).
* House 6 a terraced house with 3 floors in Udine, (IT). The residents are a mature couple (1 working part-time and 1 full time), living with two young children.
* House 7 a detached house with 2 floors in Basiliano (IT). The residents are a retired couple, spending most of time at home.

The outlets are connected as follows:
0 Coffee machine, washing machine, radio, water kettle, fridge w/ freezer, dishwasher, kitchen lamp, TV, vacuum cleaner
1 Fridge, dishwasher, microwave, water kettle, washing machine, radio w/ amplifier, dryier, kitchenware (mixer and fruit juicer), bedside light
2. TV, NAS, washing machine, drier, dishwasher, notebook, kitchenware, coffee machine, bread machine
3. Entrance outlet, Dishwasher, water kettle, fridge w/o freezer, washing machine, hairdrier, computer, coffee machine, TV
4. Total outlets, total lights, kitchen TV, living room TV, fridge w/ freezer, electric oven, computer w/ scanner and printer, washing machine, hood
5. Plasma TV, lamp, toaster, stove, iron, computer w/ scanner and printer, LCD TV, washing machine, fridge w/ freezer
6. Total ground and first floor (including lights and outlets, with whitegoods, air conditioner and TV), total garden and shelter, total third floor.
7. TV w/ decoder, electric oven, dishwasher, hood, fridge w/ freezer, kitchen TV, ADSL modem, freezer, laptop w/ scanner and printer

If you notice, it's always 9 outlet per house, so just split the sentences by comma and you get the device or device groups connected to each.

For instance:

House 7
1. TV w/ decoder,
2. electric oven,
3. dishwasher, 
4. hood, 
5. fridge w/ freezer, 
6. kitchen TV, 
7. ADSL modem, 
8. freezer, 
9. laptop w/ scanner and printer

Best,
Andrea M.

P.S. the column names you see in the CSV are the mac addresses of the plugwise smart outlets used for the measurement campaign.
