### ISSUE TITLE
AMPDS database error

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#631]
Cannot load AMPDS CSV file. Any suggestions?

![image](https://user-images.githubusercontent.com/19215185/34853290-0b664842-f787-11e7-9887-030379f28008.png)

**Comment by nipunbatra** [comment]
I'm not sure if you're calling this correctly. Pining @smakonin.

**Comment by PMeira** [comment]
Please don't upload screenshots, they're terrible for archiving, searching and reproducing issues.

AMPds was moved to Harvard's Dataverse and there is a new version. 

The old version (R2013) can still be downloaded but the default format is TSV (TAB separated) instead of CSV. You need to manually click the download button and choose CSV for each file you want to download. Besides that, the timestamp column was changed to "TS". It's available at:

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/MXB7VO

The new version of the files (AMPds2) from May/2016, also hosted on Dataverse, apparently changes the headers and filenames, so it's not compatible. We'll probably need new metadata files too.

So, use the R2013 version until we have a converter for the new version. 

I added a couple of fixes in https://github.com/nilmtk/nilmtk/commit/5765231bd52cd2626dde90fe76e5ebe86c6175ee and tested it. 

I'm closing this. If there are more issues, please reopen.
