### ISSUE TITLE
Exporting Train Model

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#698]
Hello
I know there is a way to export the learnt model. But i am not sure how to use the export_model command. Any help on it would be great.

Regards

**Comment by PMeira** [comment]
The idea is explained [here](https://github.com/nilmtk/nilmtk/blob/3e6810fabecf13e815b9d93284ca4ee16819d03d/docs/manual/development_guide/writing_a_disaggregation_algorithm.md#model-loading-and-saving), you could use `export_model` and `import_model` so you don't need to retrain.

**But...** since Hart85 still have some issues that need to be investigate, the only disaggregator with some support is CombinatorialOptimisation. 

Independent of `export_model`, as long as the model is serializable (you can "pickle" it), you could always manually save it to disk and restore it later with a bit more work. You'd need to study the internals of each method to ponder whether that'd be useful for you situation.
