### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by tatianipivem** [nilmtk/nilmtk#705]
Hi, I am trying to understand and test the NILMTK in order to obtain some results in disaggregation, but everytime that I run the code, I get the output message: "Process finished with exit code -1073741819 (0xC0000005)"

It starts properly, and run some percentage of the code, but before it reaches the end,the compiler shows me the message.

By searching on the web, I found various suggestions, like:
Try to include all the interpreters folders in the environment variables (ok, I did it but nothing changed).
Try to run as administrator  (ok, I did it but nothing changed).
Try to update libraries like sklearn (ok, I did it but nothing changed).
Reinstall all libraries (ok, I did it more than once, but nothing changed).
Remove files remaining for the older packages after the packages actualization (ok, I did it ut nothing changed).

My versions are showed by the command:
from nilmtk.utils import show_versions;
show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 3.8.1
pip: 18.0
setuptools: 40.4.3
Cython: None
numpy: 1.15.2
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 5.8.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.3.0
numexpr: 2.6.8
feather: None
matplotlib: 1.4.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext)
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

Date: 2018-09-28 08:24:16.589000
Platform: Windows-10-10.0.17134
System version: 2.7
nilmtk version: 0.2.1
nilm_metadata version: 0.2.2
numpy version: 1.15.2
matplotlib version: 1.4.1
pandas version: 0.23.4
sklearn version: 0.17.1
hmmlearn version: 0.2.0

Process finished with exit code 0

Do you have any suggestion on how to solve this problem?

Thank you very much,

Best Regards,

Tatiani

**Comment by tatianipivem** [comment]
Hi PMeira,

I mean by "the code" every try that I have made. 


**Example:** 
```
from nilmtk.dataset_converters import convert_redd
convert_redd('low_freq', 'redd.h5')

```
**Output message:**
C:\Users\Engenharia\PycharmProjects\novotati\venv\Scripts\python.exe C:/Users/Engenharia/PycharmProjects/novotati/nilmtk/testex.py
Loading house 1... 1 
Process finished with exit code -1073741819 (0xC0000005)


The same occurs when I have tried to run the tests present in the folder tests.

**Example** 
test_combinatorial_optimisation.py

**Output message:**
Testing started at 10:08 AM ...
C:\Users\Engenharia\PycharmProjects\novotati\venv\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.3\helpers\pycharm\_jb_unittest_runner.py" --path C:/Users/Engenharia/PycharmProjects/novotati/nilmtk/nilmtk/tests/test_combinatorial_optimisation.py
Launching unittests with arguments python -m unittest discover -s C:/Users/Engenharia/PycharmProjects/novotati/nilmtk/nilmtk/tests -p test_combinatorial_optimisation.py -t C:\Users\Engenharia\PycharmProjects\novotati\nilmtk\nilmtk in C:\Users\Engenharia\PycharmProjects\novotati\nilmtk\nilmtk

Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'

Process finished with exit code -1073741819 (0xC0000005)


Thank you for the suggestion, so I will proceed with python 3.6 64 bits installation!

Regards,

**Comment by PMeira** [comment]
@tatianipivem Thanks for providing more info.

The list of recommended versions for the packages is currently provided in https://github.com/nilmtk/nilmtk/blob/master/environment.yml -- I just updated it to avoid the scikit-learn 0.20, which was released 2 days ago. All basic tests run fine with this list. If you can use Anaconda, you can download this `environment.yml` and then create an environment running `conda env create -f environment.yml`.

It seems the code 0xC0000005 is a general access violation error. From a quick glance, the scikit-learn and hmmlearn versions you listed are very old for using the current NILMTK codebase.  Since your NumPy is up-to-date, I'd guess the error could be due to a version mismatch between NumPy and scikit-learn. NILMTK itself is a pure Python package right now, so the issue you found was probably a conflict between some of the dependencies that use Python's C API.

*A quick note:* hmmlearn is the only package that's not available neither in the official conda channels nor via pip. You need either to install Visual Studio build tools or you can install the package with `conda install -c pmeira hmmlearn`, which will use the package from my personal channel. A beta version of NILMTK 0.3 is available in that channel too but it's not updated at the moment.

**Comment by PMeira** [comment]
I'm assuming this was resolved, so I'm closing it. Feel free to reopen.
