### ISSUE TITLE
Hart 85 - Active and Reactive power

### ISSUE THREAD

**Issue by ilia200** [nilmtk/nilmtk#714]
Hi guys,
I read a few posts regarding training and disaggregating Hart 85 using both active and reactive power.
So, to my knowledge the option is there but it is blocked due to bugs.
in the file named **'hart85.py'** the function that trains, sets by default only active power : 
def train(self, metergroup, **columns=[('power', 'active')]**
I tried to change it to [('power','active'), ('power', 'reactive')] using AMPDS data base but later got an error while disaggregating.
**So is there a option to train and disaggregate Hart85 both active and reactive?**
Thanks a lot for your help

**Comment by ilia200** [comment]
Made some progress,
It seems that there is some issue with pandas with the code line in hart_85 (when using 2d data):
 return pd.DataFrame(power_chunk_dict, index=chunk.index)

the error is:
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional

solution: MultiIndex columns should probably fix that.

**Comment by PMeira** [comment]
@ilia200 The Hart85 code was broken for a couple of years, I started fixing it but it's probably not fully functional yet. 

I'm avoiding some changes related to Pandas right now since I'm waiting for Pandas v0.24 to be released (still a couple of months late) and that will bring a lot of changes: https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v0.24.0.rst

We will retest and fix most of the code after that and finally reach a more stable NILMTK v0.3.

> solution: MultiIndex columns should probably fix that.

You are probably right. I had to manually add a MultiIndex in a couple of places that implicitly created them before.

**Comment by nipunbatra** [comment]
@rajatgupta1234 Please could you look into this issue? This would need you to have some study of Hart's algorithm.

**Comment by rajatgupta1234** [comment]
@ilia200  and @PMeira 
The disaggregate function doesn't give error with pandas version 0.24. 
`def train(self, metergroup, columns=[('power', 'active'), ('power', 'reactive')],` works with this pandas version.

**Comment by rajatgupta1234** [comment]
@ilia200  @PMeira 
The issue has been solved. 
`h.train(mains,columns=[('power','active'),('power','reactive')])` works fine without any error.
`output = HDFDataStore('output.h5', 'w')
df=h.disaggregate(mains,output)`  also works fine now. 
#794  has been merged.
