### ISSUE TITLE
sample_period 

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#718]
Hi guys,
when we put sample_period = 60 for example are we doing the mean of 60 values or just take the 60th value ? 
Thank you

**Comment by PMeira** [comment]
Thanks for asking, I found an issue in that and just fixed it.

> are we doing the mean of 60 values 

The intention was that it should default to that, the mean (plus forward filling), for backwards compatibility with NILMTK v0.2 (more specifically, old Pandas versions), but something changed and I didn't notice that the order was wrong -- that is, until a couple of minutes ago, it was just forward filling without the mean.

You can use the `resample_kwargs` argument to fine tune that -- most of the parameters are passed directly to the [`resample` method from Pandas](https://pandas.pydata.org/pandas-docs/version/0.22.0/generated/pandas.DataFrame.resample.html) or call the equivalent method of the resampler object in case of `fill_method` and `how`.

For example, if you rather use the maximum instead of the default (mean):
```
meter.load(sample_period=60, resample_kwargs={'how': 'max'})
```

> or just take the 60th value ?

For that, you can now use something like:
```
meter.load(sample_period=60, resample_kwargs={'how': None})
```
