### ISSUE TITLE
Inconsistency in IAWE dataset

### ISSUE THREAD

**Issue by pawan47** [nilmtk/nilmtk#756]
While exploring the dataset, I found that in many instances (also in good section) the power consumption of fridge was higher than that of mains. Please comment about the same.

**Comment by nipunbatra** [comment]
@pawan47 
please provide a minimal working example code so that we can quickly verify what you're saying.

**Comment by pawan47** [comment]
please find the following code 

```
import pandas as pd
import numpy as np

ref = pd.read_csv('3.csv',low_memory = False)
mains = pd.read_csv('1.csv',low_memory = False)

mains_power = mains.W.values
ref_power = ref.W.values

#finding intersection between time stamp
s1 = mains.timestamp.values
s2 = ref.timestamp.values
intr = list(set(s1).intersection(set(s2)))   #finding intersection between two sets

#finding power based on common time stamp
ref_power_intr = ref_power[np.nonzero(np.in1d(s2,np.array(intr)).astype('int'))[0]]
mains_power_intr = mains_power[np.nonzero(np.in1d(s1,np.array(intr)).astype('int'))[0]]
``` 
when you look at the initial power array of both mains and fridge, you can observe the inconsistency. Like in the following example:


![example](https://user-images.githubusercontent.com/28859302/58326016-321d3c80-7e49-11e9-9626-1d6f0401f1ff.png)


As you can see the power of fridge is greater than the power of the main meter power reading. 
If I am wrong please correct me

**Comment by nipunbatra** [comment]
Did you use data from 13 July and 4th August 2013? As mentioned on the dataset page: https://iawe.github.io/
that time period is the best to use. NILMTK HDF5 is created from the same timerange.

Secondly, mains is spread across 1.csv and 2.csv. You should first add the data from 1.csv and 2.csv and then compare with 3.csv

I can confirm that I see no problem. The readings are as expected.

```python
import pandas as pd
df1 = pd.read_hdf("/home/nipunbatra-pc/Downloads/iawe.h5",'/building1/elec/meter1/').resample('1T').mean()
df2 = pd.read_hdf("/home/nipunbatra-pc/Downloads/iawe.h5",'/building1/elec/meter2/').resample('1T').mean()
df3 = pd.read_hdf("/home/nipunbatra-pc/Downloads/iawe.h5",'/building1/elec/meter3/').resample('1T').mean()
df_mains = df1 + df2

df_mains[('power','active')].plot(label='Mains')
df3[('power','active')].plot(label='Fridge')
import matplotlib.pyplot as plt
plt.legend()
```

![Figure_1](https://user-images.githubusercontent.com/60985/58327351-000dd980-7e4d-11e9-8593-856786a8e47f.png)

You can find the download link for HDF5 here: https://iawe.github.io/

Instead of the method I used, you should ideally use NILMTK to do the same.
