### ISSUE TITLE
set the number of states in FHMM

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#772]
HI,

I'am trying to set the number of states during the training using "num_states_dict= {}" in the train function but it doesn't work  do I need to put a numer or strings or what ?
fhmm.train(top_5_train_elec, num_states_dict= {??}, sample_period=60)
Thank you

**Comment by nipunbatra** [comment]
Please see in the code here:



        for i, meter in enumerate(metergroup.submeters().meters):
            power_series = meter.power_series(**load_kwargs)
            meter_data = next(power_series).dropna()
            X = meter_data.values.reshape((-1, 1))
            
            if not len(X):
                print("Submeter '{}' has no samples, skipping...".format(meter))
                continue
                
            assert X.ndim == 2
            self.X = X

            if num_states_dict.get(meter) is not None:
                # User has specified the number of states for this appliance
                num_total_states = num_states_dict.get(meter)

You need to pass in a dictionary with key as appliance and the value as the number of states.

@raktim2015: Please could you test and add to the documentation. I think this existed in documentation somewhere at some point of time.

**Comment by raktim2015** [comment]
@nipunbatra I have tested it on REDD dataset. It is working fine with `fhmm.train(top_5_train_elec, num_states_dict={"fridge":2,"light":2},sample_period=60)`.  
Should I add it to Training and Disaggregation -> FHMM ?

**Comment by nipunbatra** [comment]
Verify the individual states of the learnt HMM. Also do try with say states = 5 for some appliance.

Yes, please do add it in training and disaggregatioj notebook and also in docstring.

**Comment by walidsliti** [comment]
thanks for your replies @nipunbatra  and @raktim2015 ,
 I changed the number of states to 5 and nothing changed
I tried this with dish washer and heater from the REFIT dataset
thanks

**Comment by nipunbatra** [comment]
@raktim2015 can you please confirm @walidsliti finding?

**Comment by raktim2015** [comment]
Yes. The same thing also happened to me. I didn't find any difference in predicted data

**Comment by walidsliti** [comment]
HI guys
is there anything new for how setting the number of states ?
Thanks

**Comment by PMeira** [comment]
The issue here was that instead of the appliance string, it expected the meter as seem from 

> if num_states_dict.get(meter) is not None:

I changed it to meet the expectations and it now allows meter instances, an appliance object instance, or an appliance name (it doesn't try to match synonyms though). So, `fhmm.train(top_5_train_elec, num_states_dict={"fridge":2,"light":2})` should be working now in the master branch.

I also changed it to be more explicit -- if the user finds the number of states is absurd for that meter, they find that right now instead of having to wait for the full results, plotting, etc.

> Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])' **with 2 states**

Here's an example prediction from a modified disaggregation_and_metrics.ipynb using 2 and 3 states for the fridge

![fhmm_states](https://user-images.githubusercontent.com/10246101/60563845-c9708c00-9d33-11e9-8b59-d0c7114c5847.png)

(Sidenote: remember to reopen the issue tickets if there are still issues related to the main issue theme, otherwise they can get lost by the way GitHub gives priority to open issues.)
