### ISSUE TITLE
house_2 REDD and FHMM

### ISSUE THREAD

**Issue by Wusir2018** [nilmtk/nilmtk#818]
hello to all

When I read your article about FHMM, I have some question.
n is the number of devices, each device has a discrete hidden state, denoted x(i)t∈{1, . . . ,Ni} for the state at time t for device i.
At each time t, given the internal state, the ith device emits a Gaussian distributed power, denoted y(i)t, however, we only observe the sum of all the power outputs at each time, so how can we get the y(i)t ? And how can we calculate the emission matrix B?

And if I want to test the house_2 of REED by FHMM, I want to get the result about the hidden state about the every device in channel_1.dat, could you give me example?

**Comment by PMeira** [comment]
> When I read your article about FHMM, I have some question.

(Not the author here)
First the model is trained using data from individually metered devices/subcircuits. Then you can apply to the total power series to disaggregate it.

Note that the current FHMM implementation has limitations in the number of appliances due to combinatorial explosion. 

After training a FHMM instance in NILMTK, you can look into the underlying model in the `model` field, which contains the `transmat_` matrix. You can check the docs at https://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn.hmm.GaussianHMM for some more details.

> And if I want to test the house_2 of REED by FHMM, I want to get the result about the hidden state about the every device in channel_1.dat, could you give me example?

There are some examples like this one:

https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb

**Comment by Wusir2018** [comment]
Thanks for your reply !
When I read the example in this link, I have some problem about "max_num_clusters = 2 and max_num_clusters = 3" why chose 2 or 3 in this FHMM train? what's the meaning?
![QQ截图20190821160824](https://user-images.githubusercontent.com/51500032/63414855-46181080-c42f-11e9-9c1f-ffd08b490298.png)
[https://github.com/nilmtk/nilmtk/blob/master/nilmtk/disaggregate/fhmm_exact.py](url)

**Comment by Wusir2018** [comment]
@PMeira 
Thanks for your reply !
When I read the example in this link, I have some problem about "max_num_clusters = 2 and max_num_clusters = 3" why chose 2 or 3 in this FHMM train? what's the meaning?
![QQ截图20190821160824](https://user-images.githubusercontent.com/51500032/63423721-7e274f80-c43f-11e9-8cd8-966816a04228.png)
[https://github.com/nilmtk/nilmtk/blob/master/nilmtk/disaggregate/fhmm_exact.py](url)

**Comment by PMeira** [comment]
@Wusir2018 That's to try to reduce the memory used (due to the combinatorial explosion I mentioned). The memory of the computer may probably be exhausted anyway before 12 meters/appliances. See the code for the `_check_memory function` for an approximation of the memory used for the combined state transition matrix.

**Comment by Wusir2018** [comment]
@PMeira 
Thank you very much！
This max_num_clusters =2 means that the hidden state is two : On and Off ? So what does this 3 stand for?

**Comment by Wusir2018** [comment]
@PMeira 
I'm sorry to disturb you again. I have a small question. Why  rank the parameters such as the transition matrix and startprob? What is the meaning?

**Comment by PMeira** [comment]
> This max_num_clusters =2 means that the hidden state is two : On and Off ? So what does this 3 stand for?

@Wusir2018 Many appliances have more than 2 (power) states. Sometimes is better to use just 2. You can fine tune that with the `num_states_dict` passed to the `train` method.

> Why rank the parameters such as the transition matrix and startprob? What is the meaning?

It changed a bit since then, but take a look at this: https://nbviewer.jupyter.org/github/nilmtk/nilmtk/blob/v0.1.0/notebooks/fhmm.ipynb

**Comment by Wusir2018** [comment]
@PMeira 
Thank you very much！

**Comment by Wusir2018** [comment]
@PMeira 
Hello!
In this link,
[https://nbviewer.jupyter.org/github/nilmtk/nilmtk/blob/v0.1.0/notebooks/fhmm.ipynb](url)

I know the purpose of   `def decode_hmm`  is to get the power, but I can't understand how this code  realize the function. Why did you calculate power in this way? 
`for i in range(length_sequence):
        factor=total_num_combinations
        for appliance in appliance_list:
            #assuming integer division (will cause errors in Python 3x)
            factor=factor//len(centroids[appliance])
            
            temp=int(states[i])/factor
            hmm_states[appliance][i]=temp%len(centroids[appliance])
            hmm_power[appliance][i]=centroids[appliance][hmm_states[appliance][i]]`
Could you help me?
Thank you!
