### ISSUE TITLE
Questions for implementing GSP algorithm in NILMTK

### ISSUE THREAD

**Issue by nicolascassia** [nilmtk/nilmtk#823]
Hi,
I will try to write the GSP algorithm described in "On a Training-Less Solution for Non-Intrusive Appliance Load Monitoring Using Graph Signal Processing"  and I want to write it for NILMTK communty.

I read  following link:
https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/writing_a_disaggregation_algorithm.md

And I have the following questions:

1) In the paper the algorithm is described as a training less. Could  I skip train method? Or should I have to take the clustering part as the training in the algorithm? 

2)  In the clustering part I have to build a grapth using **all** samples. Is it possible write it in the "chunk-by-chunk" form? How can I do that?

Thanks in advance!

**Comment by Rithwikksvr** [comment]
Hey @nicolascassia 

There has been a change in the way algorithms are written for NILMTK.  We currently developed a rapid experimentaion API, which can be used to decrease the effort put into writing an algorithm for nilmtk community.   Refer to this [notebook](https://github.com/nilmtk/nilmtk-contrib/blob/master/Using%20Mean%20with%20Experiment%20API.ipynb) on how to use the API. 

New algorithms can be developed similar to this [file](https://github.com/nilmtk/nilmtk-contrib/tree/master/disaggregate).

Since we took this step recently, you might not be to find a document for developing a new algorithm using the latest method. But, the comments in the mean.py should be sufficient to develop a new algorithm. We can collaborate together to develop this new algorithm. I also tried to implement GSP paper for NILMTK community, but it didn't workout since I hit a few roadblocks in between. 

Feel free to contact me if you face any issues.

**Comment by nicolascassia** [comment]
Hey @Rithwikksvr 

Thank you very much for the info! I'm going to read the links but first I will try to write the algoritmh in simple python to be sure I uderstand and I could  reproduce at least some of the results of the paper.

Of course we can have a call and collaborate together. 

Thanks!
