### ISSUE TITLE
nilmtk csv exporter fails for DualSupply appliances.

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#84]
It may be a bit non-trivial this case, both while serializing/deserializing and other operations down the pipeline.

**Comment by manojm18** [comment]
@nipunbatra @JackKelly 
hi,
I have downloaded Pecan Dataport using download_dataport.py from NILM dataset converter. I would like to convert this data into CSV. I could, however, download CSV format using PostgreSQL, but i believe it only offers hourly sample. Since the download from download_dataport.py gives a mintely sample, i would like to convert this to CSV.
does the datastore offer this feature ? how can i convert h5 to CSV before disaggregating ?

**Comment by nipunbatra** [comment]
The H5 is essentially a Pandas HDF5 file. It should be straightforward to convert to CSV. See docs here: http://pandas.pydata.org/pandas-docs/stable/io.html#io-hdf5

1. load HDF5 into memory
2. write chosen dataframe to disk as CSV

1. 

1.
