### ISSUE TITLE
module 'matplotlib.dates' has no attribute '_to_ordinalf'

### ISSUE THREAD

**Issue by dungdao191299** [nilmtk/nilmtk#906]
Hello, i am a newbie and i follow install_user. When i run command in step 5 : 
`python -c "import nilmtk"`
i received a issue: 
`
AttributeError: module 'matplotlib.dates' has no attribute '_to_ordinalf'
`
![Annotation 2020-12-10 211053](https://user-images.githubusercontent.com/54898195/101783045-5b391700-3b2c-11eb-9de5-56278d94dcc1.png)

**Comment by PMeira** [comment]
Instead of just `conda install -c nilmtk nilmtk`, specify the version with `conda install -c nilmtk nilmtk=0.4.2`.  I updated the installation instructions to include this.

Using `conda env create -f=https://raw.githubusercontent.com/nilmtk/nilmtk/master/environment.yml` also creates a correct environment, even though the basic versions of the packages are the same there as the `nilmtk` package.

conda's dependency solver is very finicky (and slow), and doesn't give a warning that it's not installing the latest version of the package. It's a good idea to check the list of packages to ensure it's installing what you instructed it. We should test [mamba](https://github.com/mamba-org/mamba) for the next releases, it's a faster alternative.

**Comment by nipunbatra** [comment]
I’ve also heard good things about mamba
