### ISSUE TITLE
AMPds  Convert doesn't work

### ISSUE THREAD

**Issue by camilomarino** [nilmtk/nilmtk#907]
The function documentation suggests downloading the dataset from this url: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/MXB7VO, which is an old version of the dataset.

When I tried to convert this version of the dataset, errors occurred, since I was trying to convert "csv" corresponding to gas measurements.  The solution was to manually delete "WHG.csv", "FRG.csv", "WHW.csv" and "HTW.csv".

Also, when trying to use version 2 of the dataset, which is the newest, the converter does not work properly either. But inside the zip of version 2 of the dataset, there is an "AMPds2.h5" perfectly compatible with nilmtk.DataSet

**Comment by PMeira** [comment]
There's an on-going ticket at #682 tracking this, and a PR with some changes at #850.

> The solution was to manually delete "WHG.csv", "FRG.csv", "WHW.csv" and "HTW.csv".

Like many of the other datasets, where and how this dataset is hosted has changed through the years. But yeah, deleting non-electric data is the simplest solution if you downloaded unrelated files. Certainly the docs of the converter could include this.

> the converter does not work properly either.

That's expected. AFAIK, there was never any coordination to keep the format compatible with any of the datasets. It's one of the hurdles for NILMTK.
Note that I consider different versions of the datasets different datasets due to reproducibility and such.

> Also, when trying to use version 2 of the dataset, which is the newest, the converter does not work properly either. But inside the zip of version 2 of the dataset, there is an "AMPds2.h5" perfectly compatible with nilmtk.DataSet

Good to know, that's ideal then. We're also investigating a more stable format than Pandas-based HDF5 files to facilitate distribution so hopefully long-term we'll have a more stable format, hopefully more easily accessible by other tools besides Pandas. For Pandas, specifically, new versions usually can read files created with older versions (the inverse is not true).
