### ISSUE TITLE
AssertionError: when trying to load iawe-dataset (or any other) with nilmtk DataSet

### ISSUE THREAD

**Issue by Raphael164** [nilmtk/nilmtk#960]
Hello, could not find a solution anywhere else. So I started a new topic.
Unfortunately I have problems when loading datasets. Loading via HDFStore from pandas is possible. 
Is nilmtk installed correctly? How can I double check this?

thanks in advance

![image](https://user-images.githubusercontent.com/124141239/221150767-d7a10d25-0597-4f84-8a0d-436645ae8716.png)

![image](https://user-images.githubusercontent.com/124141239/221151884-762e1992-f9f7-4def-a26e-89c4bde98ecc.png)

**Comment by crn565** [comment]
I have  the same problem running nilmtk in ubuntu  but  I have  two  installations of nilmtk in two different machines with Windows 11  and works very well  without any problem.   This week  I have had very much problems installing nilmtk in Ubuntu ( with this guide https://soloelectronicos.com/2023/03/12/instalacion-desde-cero-de-nilmtk-en-ubuntu/)   and I think that the  problem is of the installation specially because not works in nilmtk-env

**Comment by Raphael164** [comment]
For me reinstalling the nilm_metadata with the newest version solved the problem (i am on windows):

`pip uninstall nilm_metadata
`
`pip install git+https://github.com/nilmtk/nilm_metadata`

**Comment by crn565** [comment]
thank you very much
Now  It works loading the dataset, but unfortunatelly  fails in other sentences because is using  python3.9  ( I don't know why)

**Comment by Raphael164** [comment]
Are you able to downgrade your python version to 3.8 or lower? If so, it should solve your problems.

**Comment by crn565** [comment]
A lot of thanks Raphael . Before a lot of tests I have installed  finally  the NILMTK in Ubuntu without conda (https://soloelectronicos.com/2023/03/12/instalacion-desde-cero-de-nilmtk-en-ubuntu/)   
The problem was in fact the versions of Python ( when installing Anaconda load a Python 3.9 but NILMTK only works with Python 3.8)
